import { PlaceHolderImages } from './placeholder-images';

export type Series = {
  id: number;
  title: string;
  description: string;
  rating: number; // out of 5
  imageUrl: string;
  imageHint: string;
  isFavorite: boolean;
};

const seriesBaseData = [
  { id: 67, title: 'Game of Thrones', isFavorite: true, imageId: 'series-1' },
  { id: 31, title: 'White Collar', isFavorite: true, imageId: 'series-2' },
  { id: 1, title: 'Suits', isFavorite: true, imageId: 'series-3' },
  { id: 86, title: 'Los hombres del SAS', isFavorite: true, imageId: 'series-4' },
  { id: 62, title: 'The Mandalorian', isFavorite: true, imageId: 'series-5' },
  { id: 2, title: 'Brooklyn 99', isFavorite: true, imageId: 'series-6' },
  { id: 3, title: 'That \'70s Show', isFavorite: true, imageId: 'series-7' },
  { id: 4, title: 'Peaky Blinders', isFavorite: true, imageId: 'series-8' },
  { id: 5, title: 'Blindspot', isFavorite: true, imageId: 'series-9' },
  { id: 6, title: 'Shooter', isFavorite: false, imageId: 'series-10' },
  { id: 7, title: 'Better Call Saul', isFavorite: true, imageId: 'series-11' },
  { id: 8, title: 'Breaking Bad', isFavorite: true, imageId: 'series-12' },
  { id: 9, title: 'Bojack Horseman', isFavorite: true, imageId: 'series-13' },
  { id: 10, title: 'Blacklist', isFavorite: true, imageId: 'series-14' },
  { id: 11, title: 'Orange Is the New Black', isFavorite: false, imageId: 'series-15' },
  { id: 12, title: 'The Good Place', isFavorite: false, imageId: 'series-16' },
  { id: 13, title: 'Bodyguard', isFavorite: true, imageId: 'series-17' },
  { id: 14, title: 'The Fresh Prince of Bel-Air', isFavorite: false, imageId: 'series-18' },
  { id: 15, title: 'Elite', isFavorite: true, imageId: 'series-19' },
  { id: 16, title: 'Club de Cuervos', isFavorite: true, imageId: 'series-20' },
  { id: 17, title: 'Designated Survivor', isFavorite: true, imageId: 'series-21' },
  { id: 18, title: 'La Casa de Papel', isFavorite: true, imageId: 'series-22' },
  { id: 19, title: 'Stranger Things', isFavorite: false, imageId: 'series-23' },
  { id: 20, title: 'The Society', isFavorite: false, imageId: 'series-24' },
  { id: 21, title: '13 Reasons Why', isFavorite: false, imageId: 'series-25' },
  { id: 22, title: 'The Good Cop', isFavorite: false, imageId: 'series-26' },
  { id: 23, title: 'Sex Education', isFavorite: false, imageId: 'series-27' },
  { id: 24, title: 'How to Sell Drugs Online (Fast)', isFavorite: false, imageId: 'series-28' },
  { id: 25, title: 'Baby', isFavorite: true, imageId: 'series-29' },
  { id: 26, title: 'Manhunt: Unabomber', isFavorite: false, imageId: 'series-30' },
  { id: 27, title: 'Friends', isFavorite: false, imageId: 'series-31' },
  { id: 28, title: 'The I-Land', isFavorite: false, imageId: 'series-32' },
  { id: 29, title: 'Big Mouth', isFavorite: false, imageId: 'series-33' },
  { id: 30, title: 'F is for Family', isFavorite: false, imageId: 'series-34' },
  { id: 32, title: 'Lucifer', isFavorite: true, imageId: 'series-35' },
  { id: 33, title: 'Ragnarok', isFavorite: false, imageId: 'series-36' },
  { id: 34, title: 'Me, Iglesias', isFavorite: false, imageId: 'series-37' },
  { id: 35, title: 'Luis Miguel: The Series', isFavorite: false, imageId: 'series-38' },
  { id: 36, title: 'K.C. Undercover', isFavorite: false, imageId: 'series-39' },
  { id: 37, title: 'Mindhunter', isFavorite: false, imageId: 'series-40' },
  { id: 38, title: 'The Good Place', isFavorite: false, imageId: 'series-41' },
  { id: 39, title: 'Arrow', isFavorite: false, imageId: 'series-42' },
  { id: 40, title: 'The Flash', isFavorite: false, imageId: 'series-43' },
  { id: 41, title: 'DC\'s Legends of Tomorrow', isFavorite: false, imageId: 'series-44' },
  { id: 42, title: 'Supergirl', isFavorite: false, imageId: 'series-45' },
  { id: 43, title: 'Agents of S.H.I.E.L.D.', isFavorite: false, imageId: 'series-46' },
  { id: 44, title: 'Gossip Girl', isFavorite: false, imageId: 'series-47' },
  { id: 45, title: 'The Vampire Diaries', isFavorite: true, imageId: 'series-48' },
  { id: 46, title: 'The Originals', isFavorite: false, imageId: 'series-49' },
  { id: 47, title: 'The Client List', isFavorite: true, imageId: 'series-50' },
  { id: 48, title: 'You Me Her', isFavorite: false, imageId: 'series-51' },
  { id: 49, title: 'Locke & Key', isFavorite: false, imageId: 'series-52' },
  { id: 50, title: 'Toy Boy', isFavorite: false, imageId: 'series-53' },
  { id: 51, title: 'Vivir sin permiso', isFavorite: true, imageId: 'series-54' },
  { id: 52, title: 'Too Hot to Handle', isFavorite: false, imageId: 'series-55' },
  { id: 53, title: 'Paradise PD', isFavorite: false, imageId: 'series-56' },
  { id: 54, title: 'Outer Banks', isFavorite: true, imageId: 'series-57' },
  { id: 55, title: 'Control Z', isFavorite: false, imageId: 'series-58' },
  { id: 56, title: 'Workin\' Moms', isFavorite: false, imageId: 'series-59' },
  { id: 57, title: 'The Witcher', isFavorite: false, imageId: 'series-60' },
  { id: 58, title: 'Dynasty', isFavorite: true, imageId: 'series-61' },
  { id: 59, title: 'Prison Break', isFavorite: true, imageId: 'series-62' },
  { id: 60, title: 'Cobra Kai', isFavorite: true, imageId: 'series-63' },
  { id: 63, title: 'WandaVision', isFavorite: false, imageId: 'series-65' },
  { id: 64, title: '9-1-1', isFavorite: false, imageId: 'series-66' },
  { id: 65, title: 'The Book of Boba Fett', isFavorite: true, imageId: 'series-67' },
  { id: 66, title: 'Obi-Wan Kenobi', isFavorite: false, imageId: 'series-68' },
  { id: 68, title: 'House of the Dragon', isFavorite: true, imageId: 'series-69' },
  { id: 69, title: 'Bridgerton', isFavorite: true, imageId: 'series-70' },
  { id: 70, title: 'Andor', isFavorite: true, imageId: 'series-71' },
  { id: 71, title: 'The Big Bang Theory', isFavorite: true, imageId: 'series-72' },
  { id: 72, title: 'Young Sheldon', isFavorite: false, imageId: 'series-73' },
  { id: 73, title: 'Ahsoka', isFavorite: false, imageId: 'series-74' },
  { id: 74, title: 'The O.C.', isFavorite: true, imageId: 'series-75' },
  { id: 75, title: 'The Night Manager', isFavorite: true, imageId: 'series-76' },
  { id: 76, title: 'The Rookie', isFavorite: true, imageId: 'series-77' },
  { id: 77, title: 'The Rookie: Feds', isFavorite: false, imageId: 'series-78' },
  { id: 78, title: 'The Gentlemen', isFavorite: false, imageId: 'series-79' },
  { id: 79, title: 'Star Wars: The Clone Wars', isFavorite: true, imageId: 'series-80' },
  { id: 80, title: 'The White Lotus', isFavorite: true, imageId: 'series-81' },
  { id: 81, title: 'The Last of Us', isFavorite: false, imageId: 'series-82' },
  { id: 82, title: 'Billions', isFavorite: true, imageId: 'series-83' },
  { id: 83, title: 'Machos Alfa', isFavorite: true, imageId: 'series-84' },
  { id: 84, title: 'Lies and Deceit', isFavorite: false, imageId: 'series-85' },
  { id: 85, title: 'Hostage', isFavorite: false, imageId: 'series-86' }
];

// Descriptions generated by AI
const descriptions: Record<string, string> = {
  'Game of Thrones': 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
  'White Collar': 'A white-collar con artist agrees to help the FBI catch other white-collar criminals using his expertise as an art and securities thief, counterfeiter, and con man.',
  'Suits': 'On the run from a drug deal gone bad, a brilliant college dropout finds himself working with Harvey Specter, one of New York City\'s best lawyers.',
  'Los hombres del SAS': 'A dramatized account of how the world\'s greatest Special Forces unit, the SAS, was formed under extraordinary circumstances in the darkest days of World War II.',
  'The Mandalorian': 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
  'Brooklyn 99': 'Jake Peralta, an immature, but talented N.Y.P.D. detective in Brooklyn\'s 99th Precinct, comes into immediate conflict with his new commanding officer, the serious and stern Captain Ray Holt.',
  'That \'70s Show': 'A comedy about a group of teenage friends, their mishaps, and their coming of age, set in 1970s Wisconsin.',
  'Peaky Blinders': 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.',
  'Blindspot': 'A mysterious tattooed woman is found naked in Times Square, with no memory of who she is or how she got there. The tattoos are clues to crimes the FBI must solve.',
  'Shooter': 'A highly decorated ex-Marine sniper is coaxed back into action to prevent a plot to assassinate the President, but he is double-crossed and framed for the attempt.',
  'Better Call Saul': 'The trials and tribulations of criminal lawyer Jimmy McGill in the time before he established his strip-mall law office in Albuquerque, New Mexico.',
  'Breaking Bad': 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
  'Bojack Horseman': 'Meet the most beloved sitcom horse of the \'90s - 20 years later. BoJack Horseman was the star of the hit TV show "Horsin\' Around," but today he\'s washed up, living in Hollywood, complaining about everything, and wearing colorful sweaters.',
  'Blacklist': 'A new FBI profiler, Elizabeth Keen, has her entire life uprooted when a mysterious criminal, Raymond Reddington, who has eluded capture for decades, turns himself in and insists on speaking only to her.',
  'Orange Is the New Black': 'Convicted of a decade old crime of transporting drug money to an ex-girlfriend, normally law-abiding Piper Chapman is sentenced to a year and a half behind bars in a women\'s prison.',
  'The Good Place': 'Four people and their otherworldly frienemy struggle in the afterlife to define what it means to be good.',
  'Bodyguard': 'A contemporary thriller featuring the Royalty and Specialist Protection Branch of London\'s Metropolitan Police Service.',
  'The Fresh Prince of Bel-Air': 'A streetwise, poor young man from Philadelphia is sent by his mother to live with his aunt, uncle and cousins in their Bel-Air mansion.',
  'Elite': 'When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.',
  'Club de Cuervos': 'A brother and sister battle for control of their family\'s professional soccer team after their father\'s death.',
  'Designated Survivor': 'A low-level Cabinet member becomes President of the United States after a catastrophic attack kills everyone above him in the line of succession.',
  'La Casa de Papel': 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.',
  'Stranger Things': 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
  'The Society': 'A group of teenagers struggles to survive after they\'re mysteriously transported to a facsimile of their wealthy New England town without any trace of their parents.',
  '13 Reasons Why': 'Follows teenager Clay Jensen, in his quest to uncover the story behind his classmate and crush, Hannah, and her decision to end her life.',
  'The Good Cop': 'An earnest, obsessively honest NYPD detective is forced to live with his dad, a disgraced, former NYPD officer who never followed the rules.',
  'Sex Education': 'A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic at school.',
  'How to Sell Drugs Online (Fast)': 'To win back his ex-girlfriend, a nerdy teen starts selling ecstasy online out of his bedroom, and becomes one of Europe\'s biggest dealers.',
  'Baby': 'Inspired by a true story, a group of Roman teenagers challenge the norms of society in a quest for identity and independence.',
  'Manhunt: Unabomber': 'An in-depth look at how an FBI profiler helped track down the Unabomber.',
  'Friends': 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.',
  'The I-Land': 'When ten people wake up on a treacherous island with no memory of who they are or how they got there, they set off on a trek to try to get back home, only to discover the world is not as it seems.',
  'Big Mouth': 'Teenage friends find their lives upended by the wonders and horrors of puberty in this edgy, adult animated comedy.',
  'F is for Family': 'Follows the Murphy family in the 1970s, a time when you could smack your kid, smoke inside and bring a gun to the airport.',
  'Lucifer': 'Lucifer Morningstar has decided he\'s had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels.',
  'Ragnarok': 'A small Norwegian town experiencing warm winters and violent downpours seems to be headed for another Ragnarok -- unless someone intervenes in time.',
  'Me, Iglesias': 'A comedy series about a well-intentioned public high school teacher who works at his alma mater.',
  'Luis Miguel: The Series': 'The story of the life of Mexican superstar singer Luis Miguel, who has captivated audiences in Latin America and beyond for decades.',
  'K.C. Undercover': 'An outspoken and confident technology wiz and skilled black belt discovers that both of her parents are spies and expect her to follow in their footsteps.',
  'Mindhunter': 'In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.',
  'Arrow': 'Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.',
  'The Flash': 'After being struck by lightning, Barry Allen wakes up from his coma to discover he\'s been given the power of super speed, becoming the Flash, fighting crime in Central City.',
  'DC\'s Legends of Tomorrow': 'Time-traveling rogue Rip Hunter has to recruit a rag-tag team of heroes and villains to help prevent an apocalypse that could impact not only Earth, but all of time.',
  'Supergirl': 'The adventures of Superman\'s cousin in her own right, who after 12 years of keeping her powers a secret on Earth, decides to finally embrace her superhuman abilities and be the hero she was always meant to be.',
  'Agents of S.H.I.E.L.D.': 'The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.',
  'Gossip Girl': 'Privileged teens living on the Upper East Side of New York can hide no secret from the ruthless blogger who is always watching.',
  'The Vampire Diaries': 'The lives, loves, dangers and disasters in the town, Mystic Falls, Virginia. Creatures of unspeakable horror lurk beneath this town as a teenage girl is suddenly torn between two vampire brothers.',
  'The Originals': 'A family of power-hungry thousand-year-old vampires look to take back the city they built and dominate all those who have done them wrong.',
  'The Client List': 'A single mother, left by her husband, takes a job at a day spa and learns that there is more to the business than just massages.',
  'You Me Her': 'A three-way romantic relationship develops between a suburban married couple and another woman.',
  'Locke & Key': 'Following their father\'s murder, three siblings move into a house filled with reality-bending keys.',
  'Toy Boy': 'A stripper sets out to prove his innocence for a crime he didn\'t commit.',
  'Vivir sin permiso': 'When a Galician tycoon with a clean-cut-businessman facade is diagnosed with Alzheimer\'s disease, he tries to keep it from his family while he starts to search for his successor.',
  'Too Hot to Handle': 'On the shores of paradise, gorgeous singles meet and mingle. But there\'s a twist. To win a $100,000 grand prize, they\'ll have to give up sex.',
  'Paradise PD': 'An eager young rookie joins the ragtag small-town police force led by his dad, and they stumble across a major drug case.',
  'Outer Banks': 'A group of teenagers from the wrong side of the tracks stumble upon a treasure map that unearths a long buried secret.',
  'Control Z': 'When a hacker starts releasing students\' secrets to the entire high school, the socially isolated but observant Sofía works to uncover the hacker\'s identity.',
  'Workin\' Moms': 'Four very different thirty-something working mothers and friends try to balance their jobs, family lives and love lives in modern day Toronto, Canada.',
  'The Witcher': 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
  'Dynasty': 'Follows two of America\'s wealthiest families as they feud for control over their fortune and their children.',
  'Prison Break': 'A structural engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.',
  'Cobra Kai': 'Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again.',
  'WandaVision': 'Living idealized suburban lives, super-powered beings Wanda and Vision begin to suspect that everything is not as it seems.',
  '9-1-1': 'Explores the high-pressure experiences of first responders -- including police officers, firefighters and dispatchers -- who are thrust into the most frightening, shocking and heart-stopping situations.',
  'The Book of Boba Fett': 'Bounty hunter Boba Fett and mercenary Fennec Shand navigate the underworld of the galaxy when they return to the sands of Tatooine to stake their claim on the territory once ruled by Jabba the Hutt.',
  'Obi-Wan Kenobi': 'Jedi Master Obi-Wan Kenobi has to save young Leia Organa from the clutches of the Inquisitors, and is forced to face his past and his former apprentice, Anakin Skywalker.',
  'House of the Dragon': 'The story of the House Targaryen, set 200 years before the events of Game of Thrones.',
  'Bridgerton': 'The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.',
  'Andor': 'The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian will embark on the path that is destined to turn him into a Rebel hero.',
  'The Big Bang Theory': 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.',
  'Young Sheldon': 'The early life of child genius Sheldon Cooper, later seen in The Big Bang Theory.',
  'Ahsoka': 'Former Jedi Knight Ahsoka Tano investigates an emerging threat to a vulnerable galaxy.',
  'The O.C.': 'A troubled youth becomes embroiled in the lives of a close-knit group of people in the wealthy, upper-class neighborhood of Newport Beach, Orange County, California.',
  'The Night Manager': 'The night manager of a Cairo hotel is recruited by intelligence agents to infiltrate the inner circle of an international arms dealer.',
  'The Rookie': 'Starting over isn\'t easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer.',
  'The Rookie: Feds': 'Follows Simone Clark, the oldest rookie in the FBI Academy, who is assigned to support the LA field office.',
  'The Gentlemen': 'When aristocratic Eddie inherits the family estate, he discovers that it\'s home to an enormous weed empire, and its proprietors aren\'t going anywhere.',
  'Star Wars: The Clone Wars': 'The Grand Army of the Republic, led by Yoda, Mace Windu, Obi-Wan Kenobi, Anakin Skywalker and other Jedi Knights, fights the New Droid Army of the Separatists.',
  'The White Lotus': 'Set in a tropical resort, it follows the exploits of various guests and employees over the span of a week.',
  'The Last of Us': 'In a post-apocalyptic world, a hardened survivor is entrusted with a 14-year-old girl who may be humanity\'s last hope.',
  'Billions': 'U.S. Attorney Chuck Rhoades goes after hedge fund king, Bobby "Axe" Axelrod, in a battle between two powerful New York figures.',
  'Machos Alfa': 'Four friends in their 40s find themselves in the middle of a masculinity crisis.',
  'Lies and Deceit': 'A literature teacher seeks justice against a surgeon she claims raped her, but he vehemently denies her accusation.',
  'Hostage': 'A thrilling drama series about a family caught in a political conspiracy.',
};

const top5Posters: Record<string, string> = {
  'Game of Thrones': 'https://image.tmdb.org/t/p/original/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
  'White Collar': 'https://image.tmdb.org/t/p/original/n2TjFma1iXkG5L7eC2f8sK7sW6.jpg',
  'Suits': 'https://image.tmdb.org/t/p/original/vHviFxO5x6flpCI0WHQ4JpP1f5s.jpg',
  'Los hombres del SAS': 'https://image.tmdb.org/t/p/original/uFMAba5Gq5I4VdY3A33y0X2L22O.jpg',
  'The Mandalorian': 'https://image.tmdb.org/t/p/original/p6t2lAdGGrTvk36H7PLi2g2Oa3j.jpg',
};


export const allSeries: Series[] = seriesBaseData.map(series => {
  const image = PlaceHolderImages.find(p => p.id === series.imageId);
  const rating = series.isFavorite ? 5 : 3;

  return {
    ...series,
    description: descriptions[series.title] || 'A great series to watch.',
    rating: rating,
    imageUrl: top5Posters[series.title] || image?.imageUrl || `https://picsum.photos/seed/${series.id}/400/600`,
    imageHint: image?.imageHint || 'tv series',
  };
});
